my_cipher = """JNRZR BNIGI BJRGZ IZLQR OTDNJ GRIHT USDKR ZZWLG OIBTM NRGJN
IJTZJ LZISJ NRSBL QVRSI ORIQT QDEKJ JNRQW GLOFN IJTZX QLFQL
WBIMJ ITQXT HHTBL KUHQL JZKMM LZRNT OBIMI EURLW BLQZJ GKBJT
QDIQS LWJNR OLGRI EZJGK ZRBGS MJLDG IMNZT OIHRK MOSOT QHIJL
QBRJN IJJNT ZFIZL WIZTO MURZM RBTRZ ZKBNN LFRVR GIZFL KUHIM
MRIGJ LJNRB GKHRT QJRUU RBJLW JNRZI TULGI EZLUK JRUST QZLUK
EURFT JNLKJ JNRXR S"""

cipher_table = {
    "A": "Q",
    "B": "C",
    "C": "X",
    "D": "G",
    "E": "B",
    "F": "W",
    "G": "R",
    "H": "D",
    "I": "A",
    "J": "T",
    "K": "U",
    "L": "O",
    "M": "P",
    "N": "H",
    "O": "M",
    "P": "J",
    "Q": "N",
    "R": "E",
    "S": "Y",
    "T": "I",
    "U": "L",
    "V": "V",
    "W": "F",
    "X": "K",
    "Y": "Z",
    "Z": "S",
    " ": " ",
    "\n": "\n"
}

def decrypt_cipher(cipher):
    decrypt_text = []
    for c in cipher:
        decrypt_text.append(cipher_table[c])
    return "".join(decrypt_text)

print(decrypt_cipher(my_cipher))

'''
THESE CHARA CTERS ASONE MIGHT READI LYGUE SSFOR MACIP HERTH
ATIST OSAYT HEYCO NVEYA MEANI NGBUT THENF ROMWH ATISK NOWNO
FCAPT AINKI DDICO ULDNO TSUPP OSEHI MCAPA BLEOF CONST RUCTI
NGANY OFTHE MOREA BSTRU SECRY PTOGR APHSI MADEU PMYMI NDATO
NCETH ATTHI SWASO FASIM PLESP ECIES SUCHH OWEVE RASWO ULDAP
PEART OTHEC RUDEI NTELL ECTOF THESA ILORA BSOLU TELYI NSOLU
BLEWI THOUT THEKE Y

THESE CHARACTERS AS ONE MIGHT READILY GUESS FORM A CIPHER THAT 
IS TO SAY THEY CONVEY A MEANING BUT THEN FROM WHAT IS KNOWN OF
CAPTAIN KIDD I COULD NOT SUPPOSE HIM CAPABLE OF CONSTRUCTING
ANY OF THE MORE ABSTRUSE CRYPTOGRAPHS I MADE UP MY MIND AT ONCE
THAT THIS WAS OF A SIMPLE SPECIES SUCH HOW EVER AS WOULD APPEAR
TO THE CRUDE INTELLECT OF THE SAILOR ABSOLUTELY INSOLUBLE WITHOUT
THE KEY
'''